# Generated by Django 5.1 on 2024-08-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_messages_conversation_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message_id',
        ),
    ]
